---
kind: pipeline
name: truffleHog

- name: TruffleHog ECR build
  image: plugins/ecr
  settings:
    context: ./ecr/
    dockerfile: ./ecr/Dockerfile
    repo: 612427630422.dkr.ecr.us-east-1.amazonaws.com/sre/moe-trufflehog
    registry: 612427630422.dkr.ecr.us-east-1.amazonaws.com
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - ${DRONE_COMMIT_BRANCH}
      - latest

trigger:
  branch: dev
  event: [ push ]
